version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./content:/sites/demo
    links:
      - php
  php:
    image: 'bitnami/php-fpm:latest'
    volumes:
      - ./content:/sites/demo
  